// Archivo principal de configuración de BIND9 en el servidor DNS esclavo.

// Carga las opciones generales del servidor:
// interfaces, recursión, allow-query, RRL y DNSSEC.
include "/etc/bind/named.conf.options";

// Carga la configuración de las zonas esclavas
// y la autenticación TSIG utilizada con el maestro.
include "/etc/bind/named.conf.local";

// Carga las zonas predeterminadas proporcionadas por BIND.
include "/etc/bind/named.conf.default-zones";
